# Unstable import formatting options
group_imports = "StdExternalCrate"
imports_layout = "HorizontalVertical"
imports_granularity = "Crate"

# Unstable comment formatting options
wrap_comments = true
format_code_in_doc_comments = true
